jobs:
  build:
    env:
      MAKE_CMD: env TRANSLATE_GLOBAL_FLAGS=--swift-friendly ENV_J2OBJC_ARCHS=macosx_iphone64
        make -j32
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: java_11_env
      run: echo "JAVA_11_HOME=$(/usr/libexec/java_home -v 11)" >> $GITHUB_ENV
    - continue-on-error: true
      uses: actions/checkout@v2
    - continue-on-error: true
      name: build_all
      run: $MAKE_CMD JAVA_HOME=$JAVA_11_HOME frameworks examples_dist
    - continue-on-error: true
      name: test_tools
      run: $MAKE_CMD JAVA_HOME=$JAVA_11_HOME test_translator test_cycle_finder test_jre_cycles
name: CI
on:
  repository_dispatch:
    types: trigger-ga___main.yml
